sxiv-scm: require imlib2 with 'X' option enabled to build
when build sxiv-scm without imlib2[X]:

image.o:image.c:function img_init: error: undefined reference to 'imlib_context_set_display'
image.o:image.c:function img_init: error: undefined reference to 'imlib_context_set_visual'
image.o:image.c:function img_init: error: undefined reference to 'imlib_context_set_colormap'
image.o:image.c:function img_render: error: undefined reference to 'imlib_context_set_drawable'
image.o:image.c:function img_render: error: undefined reference to 'imlib_render_image_part_on_drawable_at_size'
thumbs.o:thumbs.c:function tns_render: error: undefined reference to 'imlib_context_set_drawable'
thumbs.o:thumbs.c:function tns_render: error: undefined reference to 'imlib_render_image_part_on_drawable_at_size'
collect2: error: ld returned 1 exit status
make: *** [sxiv] Error 1